# Derivative of Matrix

## import library

In [9]:
import numpy as np
import matplotlib.image as img
import matplotlib.pyplot as plt
import matplotlib.colors as colors

## load image 

In [10]:
I = img.imread('.\image1.jpg')  

## check the size of image

In [11]:
n_row = I.shape[0]
n_col = I.shape[1]

print(I.shape)

(525, 788, 3)


## convert the input image into gray scale if it is color

In [12]:
if I.shape[2] == 3 :

    R = I[:, :, 0]
    G = I[:, :, 1]
    B = I[:, :, 2]
    I = (R + G + B) / 3
    print(I.shape)

(525, 788)


## normalize input image so that the range of image is $[0, 1]$

In [15]:
I = (I - np.min(I)) / (np.max(I) - np.min(I))
print(I)

[[0.63921569 0.63921569 0.63921569 ... 0.69803922 0.69803922 0.69803922]
 [0.65490196 0.65490196 0.65490196 ... 0.70196078 0.70196078 0.70196078]
 [0.65490196 0.66666667 0.66666667 ... 0.69803922 0.69803922 0.69803922]
 ...
 [0.6627451  0.64705882 0.62352941 ... 0.37254902 0.37254902 0.37254902]
 [0.59215686 0.59215686 0.59215686 ... 0.40784314 0.41960784 0.41960784]
 [0.5372549  0.56078431 0.59607843 ... 0.44313725 0.45490196 0.47843137]]


```git commit -a -m "load image" ``` \
```git push origin master```

## generate a matrix to compute the derivative in $x$-direction

In [16]:
Dx = np.eye(n_col, k=-1, dtype=np.float64) - np.eye(n_col,k=0,dtype=np.float64)

## compute the derivative of $I$ with respect to $x$-direction

In [17]:
Ix = np.dot(I, Dx)
print(Ix)

[[ 0.          0.          0.         ...  0.          0.
  -0.69803922]
 [ 0.          0.          0.         ...  0.          0.
  -0.70196078]
 [ 0.01176471  0.          0.01176471 ...  0.          0.
  -0.69803922]
 ...
 [-0.01568627 -0.02352941 -0.03529412 ...  0.          0.
  -0.37254902]
 [ 0.          0.         -0.01568627 ...  0.01176471  0.
  -0.41960784]
 [ 0.02352941  0.03529412 -0.00784314 ...  0.01176471  0.02352941
  -0.47843137]]


```git commit -a -m "compute the derivative in x-direction"``` \
```git push origin master```

## generate a matrix to compute the derivative in $y$-direction

In [19]:
Dy = np.eye(n_row, k=1, dtype=np.float64) - np.eye(n_row,k=0,dtype=np.float64)


## compute the derivative of $I$ with respect to $y$-direction

In [20]:
Iy = np.dot(Dy, I)
print(Iy)

[[ 0.01568627  0.01568627  0.01568627 ...  0.00392157  0.00392157
   0.00392157]
 [ 0.          0.01176471  0.01176471 ... -0.00392157 -0.00392157
  -0.00392157]
 [ 0.01176471  0.          0.         ...  0.          0.
   0.        ]
 ...
 [-0.07058824 -0.05490196 -0.03137255 ...  0.03529412  0.04705882
   0.04705882]
 [-0.05490196 -0.03137255  0.00392157 ...  0.03529412  0.03529412
   0.05882353]
 [-0.5372549  -0.56078431 -0.59607843 ... -0.44313725 -0.45490196
  -0.47843137]]


```git commit -a -m "compute the derivative in y-direction"``` \
```git push origin master```

## compute $L_2^2$ of the gradient of $I$

In [ ]:
norm_gradient = 

## define functions for the visualization

In [ ]:
def plot_image(I):
    
    plt.figure(figsize=(10,10))
    plt.imshow( , , )
    plt.title('input image')
    plt.axis('off')
        
def plot_image_derivative_x(Ix):
    
    plt.figure(figsize=(10,10))
    plt.imshow( , , )
    plt.title('image derivative of x')
    plt.axis('off')

    
def plot_image_derivative_y(Iy):
    
    plt.figure(figsize=(10,10))
    plt.imshow( , , )
    plt.title('image derivative of y')
    plt.axis('off')

    
def plot_norm_gradient(norm_gradient):

    plt.figure(figsize=(10,10))
    plt.imshow( , , )
    plt.title('norm gradient')
    plt.axis('off')

```git commit -a -m "define functions for the visualization"``` \
```git push origin master```

# ###################################################################

# # results

# ###################################################################

# # 01. plot the input image in gray scale

In [ ]:
plot_image(I)

# # 02. plot the derivative $I_x$ of input image in x-direction

In [ ]:
plot_image_derivative_x(Ix)

# # 03. plot the derivative $I_y$ of input image in y-direction

In [ ]:
plot_image_derivative_y(Iy)

# # 04. plot $L_2^2$ norm $I_x^2 + I_y^2$ of the gradient of input image

In [ ]:
plot_norm_gradient(norm_gradient)